return {
    ["猪仔"] = "https://github.com/XiaoYunUwU/XiaoYunUwU/raw/main/Script%2FA%E5%B0%8F%E7%8C%AA.lua",
    ["森林中的99天"] = "https://raw.githubusercontent.com/XiaoYunUwU/XiaoYunUwU/refs/heads/main/Script/%E7%94%9F%E5%AD%9899%E5%A4%A9",
    ["力量传奇"] = "https://github.com/XiaoYunUwU/XiaoYunUwU/raw/main/Script/%E5%8A%9B%E9%87%8F%E4%BC%A0%E5%A5%87",
    ["造船寻宝"] = "https://github.com/XiaoYunUwU/XiaoYunUwU/raw/main/Script/%E9%80%A0%E8%88%AC%E5%AF%BB%E5%AE%9D",
    ["火箭模拟器"] = "https://raw.githubusercontent.com/XiaoYunUwU/XiaoYunUwU/refs/heads/main/Script/%E7%81%AB%E7%AE%AD%E6%A8%A1%E6%8B%9F%E5%99%A8",
    ["吃掉世界"] = "https://github.com/XiaoYunUwU/XiaoYunUwU/raw/main/Script%2FA%E5%90%83%E4%B8%96%E7%95%8C",
    ["监狱人生 [测试版]"] = "https://raw.githubusercontent.com/XiaoYunUwU/XiaoYunUwU/refs/heads/main/Script/%E7%9B%91%E7%8B%B1%E4%BA%BA%E7%94%9F.lua",
    ["竞速火箭"] = "https://raw.githubusercontent.com/XiaoYunUwU/XiaoYunUwU/refs/heads/main/Script/%E7%AB%9E%E9%80%9F%E7%81%AB%E7%AE%AD",
    ["被遗弃"] = "https://raw.githubusercontent.com/XiaoYunUwU/XiaoYunUwU/refs/heads/main/Script/%E8%A2%AB%E9%81%97%E5%BC%83",
    ["感染性微笑"] = "https://raw.githubusercontent.com/XiaoYunUwU/XiaoYunUwU/refs/heads/main/Script/%E6%84%9F%E6%9F%93%E6%80%A7%E5%BE%AE%E7%AC%91",
    ["Break in (Story)"] = "https://github.com/XiaoYunUwU/XiaoYunUwU/raw/main/Script%2FBreak%20in",
    ["Field Trip Z"] = "https://github.com/XiaoYunUwU/XiaoYunUwU/raw/main/Script%2FField%20Trip%20Z",
    ["极速传奇"] = "https://github.com/XiaoYunUwU/XiaoYunUwU/raw/main/Script%2F%E6%9E%81%E9%80%9F%E4%BC%A0%E5%A5%87",
    ["战争大亨"] = "https://raw.githubusercontent.com/XiaoYunUwU/XiaoYunUwU/refs/heads/main/Script/%E6%88%98%E4%BA%89%E5%A4%A7%E4%BA%A8",
    ["虫脸"] = "https://raw.githubusercontent.com/XiaoYunUwU/XiaoYunUwU/refs/heads/main/Script/%E8%99%AB%E8%84%B8",
    ["Fisch"] = "https://github.com/XiaoYunUwU/XiaoYunUwU/raw/main/Script%2FFisch",
    -- ["汽车经售大亨"] = "https://raw.githubusercontent.com/XiaoYunUwU/XiaoYunUwU/refs/heads/main/Script/%E6%B1%BD%E8%BD%A6%E7%BB%8F%E5%94%AE%E5%A4%A7%E4%BA%A8.lua",
    ["忍者传奇"] = "https://github.com/XiaoYunUwU/XiaoYunUwU/raw/main/Script%2F%E5%BF%8D%E8%80%85%E4%BC%A0%E5%A5%87"
}
